# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      # This is the name of your group, it will be used in PR titles and branch names
      dependencies:
        # A pattern can be...
        patterns:
          - '*'
    ignore:
          # Starting from v0.58.0, the upstream module removes ServerIPAddrs,
          # introducing breaking change to us.
          # If we try to adapt to the change, we can only use one ip for every upstream
          # Considering no security fixes are related, we will stick to the last version 
          # before v0.58 which is v0.57.3
      - dependency-name: 'github.com/AdguardTeam/dnsproxy'
        versions: ["*"]
