#!/bin/sh /etc/rc.common
# Copyright (C) 2020 IrineSistiana

START=99
USE_PROCD=1

#####  ONLY CHANGE THIS BLOCK  ######
PROG=/usr/bin/mosdns  # where is mosdns
RES_DIR=/etc/mosdns/  # resource dir / working dir / the dir where you store ip/domain lists
CONF=./config.yaml    # where is the config file, it can be a relative path to $RES_DIR
#####  ONLY CHANGE THIS BLOCK  ######

start_service() {
	procd_open_instance
	procd_set_param command $PROG -dir $RES_DIR -c $CONF -quiet

	procd_set_param user root
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_close_instance
	echo "mosdns is started!"
}

reload_service() {
	stop
	sleep 2s
	echo "mosdns is restarted!"
	start
}
