// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: plugin/executable/cache/dump.proto

package cache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CachedEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key                 []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Msg                 []byte `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	CacheExpirationTime int64  `protobuf:"varint,3,opt,name=cache_expiration_time,json=cacheExpirationTime,proto3" json:"cache_expiration_time,omitempty"`
	MsgExpirationTime   int64  `protobuf:"varint,4,opt,name=msg_expiration_time,json=msgExpirationTime,proto3" json:"msg_expiration_time,omitempty"`
	MsgStoredTime       int64  `protobuf:"varint,5,opt,name=msg_stored_time,json=msgStoredTime,proto3" json:"msg_stored_time,omitempty"`
}

func (x *CachedEntry) Reset() {
	*x = CachedEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_executable_cache_dump_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CachedEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedEntry) ProtoMessage() {}

func (x *CachedEntry) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_executable_cache_dump_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedEntry.ProtoReflect.Descriptor instead.
func (*CachedEntry) Descriptor() ([]byte, []int) {
	return file_plugin_executable_cache_dump_proto_rawDescGZIP(), []int{0}
}

func (x *CachedEntry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CachedEntry) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *CachedEntry) GetCacheExpirationTime() int64 {
	if x != nil {
		return x.CacheExpirationTime
	}
	return 0
}

func (x *CachedEntry) GetMsgExpirationTime() int64 {
	if x != nil {
		return x.MsgExpirationTime
	}
	return 0
}

func (x *CachedEntry) GetMsgStoredTime() int64 {
	if x != nil {
		return x.MsgStoredTime
	}
	return 0
}

type CacheDumpBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*CachedEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *CacheDumpBlock) Reset() {
	*x = CacheDumpBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_executable_cache_dump_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheDumpBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheDumpBlock) ProtoMessage() {}

func (x *CacheDumpBlock) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_executable_cache_dump_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheDumpBlock.ProtoReflect.Descriptor instead.
func (*CacheDumpBlock) Descriptor() ([]byte, []int) {
	return file_plugin_executable_cache_dump_proto_rawDescGZIP(), []int{1}
}

func (x *CacheDumpBlock) GetEntries() []*CachedEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_plugin_executable_cache_dump_proto protoreflect.FileDescriptor

var file_plugin_executable_cache_dump_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x2f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x64, 0x75, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x61, 0x63, 0x68, 0x65, 0x22, 0xbd, 0x01, 0x0a, 0x0b,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12,
	0x32, 0x0a, 0x15, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x6d, 0x73, 0x67, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x11, 0x6d, 0x73, 0x67, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x6d, 0x73, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6d, 0x73,
	0x67, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x3e, 0x0a, 0x0e, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x44, 0x75, 0x6d, 0x70, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x2c, 0x0a,
	0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x42, 0x19, 0x5a, 0x17, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x2f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plugin_executable_cache_dump_proto_rawDescOnce sync.Once
	file_plugin_executable_cache_dump_proto_rawDescData = file_plugin_executable_cache_dump_proto_rawDesc
)

func file_plugin_executable_cache_dump_proto_rawDescGZIP() []byte {
	file_plugin_executable_cache_dump_proto_rawDescOnce.Do(func() {
		file_plugin_executable_cache_dump_proto_rawDescData = protoimpl.X.CompressGZIP(file_plugin_executable_cache_dump_proto_rawDescData)
	})
	return file_plugin_executable_cache_dump_proto_rawDescData
}

var file_plugin_executable_cache_dump_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plugin_executable_cache_dump_proto_goTypes = []interface{}{
	(*CachedEntry)(nil),    // 0: cache.CachedEntry
	(*CacheDumpBlock)(nil), // 1: cache.CacheDumpBlock
}
var file_plugin_executable_cache_dump_proto_depIdxs = []int32{
	0, // 0: cache.CacheDumpBlock.entries:type_name -> cache.CachedEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plugin_executable_cache_dump_proto_init() }
func file_plugin_executable_cache_dump_proto_init() {
	if File_plugin_executable_cache_dump_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plugin_executable_cache_dump_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CachedEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_executable_cache_dump_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheDumpBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plugin_executable_cache_dump_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_executable_cache_dump_proto_goTypes,
		DependencyIndexes: file_plugin_executable_cache_dump_proto_depIdxs,
		MessageInfos:      file_plugin_executable_cache_dump_proto_msgTypes,
	}.Build()
	File_plugin_executable_cache_dump_proto = out.File
	file_plugin_executable_cache_dump_proto_rawDesc = nil
	file_plugin_executable_cache_dump_proto_goTypes = nil
	file_plugin_executable_cache_dump_proto_depIdxs = nil
}
