// This proto is a copy of v2ray.com/core/app/router/config.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: pkg/cache/cache_dump.proto

package cache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CachedEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key            string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	StoreTime      int64  `protobuf:"varint,2,opt,name=store_time,json=storeTime,proto3" json:"store_time,omitempty"`
	ExpirationTime int64  `protobuf:"varint,3,opt,name=expiration_time,json=expirationTime,proto3" json:"expiration_time,omitempty"`
	Value          []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CachedEntry) Reset() {
	*x = CachedEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_cache_cache_dump_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CachedEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedEntry) ProtoMessage() {}

func (x *CachedEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cache_cache_dump_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedEntry.ProtoReflect.Descriptor instead.
func (*CachedEntry) Descriptor() ([]byte, []int) {
	return file_pkg_cache_cache_dump_proto_rawDescGZIP(), []int{0}
}

func (x *CachedEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CachedEntry) GetStoreTime() int64 {
	if x != nil {
		return x.StoreTime
	}
	return 0
}

func (x *CachedEntry) GetExpirationTime() int64 {
	if x != nil {
		return x.ExpirationTime
	}
	return 0
}

func (x *CachedEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type CacheDump struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*CachedEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *CacheDump) Reset() {
	*x = CacheDump{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_cache_cache_dump_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheDump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheDump) ProtoMessage() {}

func (x *CacheDump) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cache_cache_dump_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheDump.ProtoReflect.Descriptor instead.
func (*CacheDump) Descriptor() ([]byte, []int) {
	return file_pkg_cache_cache_dump_proto_rawDescGZIP(), []int{1}
}

func (x *CacheDump) GetEntries() []*CachedEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_pkg_cache_cache_dump_proto protoreflect.FileDescriptor

var file_pkg_cache_cache_dump_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x5f, 0x64, 0x75, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x22, 0x7d, 0x0a, 0x0b, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x39, 0x0a, 0x09, 0x43, 0x61, 0x63, 0x68, 0x65, 0x44, 0x75, 0x6d, 0x70, 0x12,
	0x2c, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x42, 0x0b, 0x5a,
	0x09, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_cache_cache_dump_proto_rawDescOnce sync.Once
	file_pkg_cache_cache_dump_proto_rawDescData = file_pkg_cache_cache_dump_proto_rawDesc
)

func file_pkg_cache_cache_dump_proto_rawDescGZIP() []byte {
	file_pkg_cache_cache_dump_proto_rawDescOnce.Do(func() {
		file_pkg_cache_cache_dump_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_cache_cache_dump_proto_rawDescData)
	})
	return file_pkg_cache_cache_dump_proto_rawDescData
}

var file_pkg_cache_cache_dump_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_cache_cache_dump_proto_goTypes = []interface{}{
	(*CachedEntry)(nil), // 0: cache.CachedEntry
	(*CacheDump)(nil),   // 1: cache.CacheDump
}
var file_pkg_cache_cache_dump_proto_depIdxs = []int32{
	0, // 0: cache.CacheDump.entries:type_name -> cache.CachedEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_cache_cache_dump_proto_init() }
func file_pkg_cache_cache_dump_proto_init() {
	if File_pkg_cache_cache_dump_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_cache_cache_dump_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CachedEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_cache_cache_dump_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheDump); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_cache_cache_dump_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_cache_cache_dump_proto_goTypes,
		DependencyIndexes: file_pkg_cache_cache_dump_proto_depIdxs,
		MessageInfos:      file_pkg_cache_cache_dump_proto_msgTypes,
	}.Build()
	File_pkg_cache_cache_dump_proto = out.File
	file_pkg_cache_cache_dump_proto_rawDesc = nil
	file_pkg_cache_cache_dump_proto_goTypes = nil
	file_pkg_cache_cache_dump_proto_depIdxs = nil
}
