name: Push to DockerHub

on:
  workflow_dispatch:
  push:
    branches:
      - "v4-maintenance"
    paths:
      - "Dockerfile"
      - ".dockerignore"
      - "go.mod"
      - "main.go"
      - "pkg/**"
      - "tools/**"
      - "coremain/**"
      - "go.sum"
      - "mlog/**"
      - "plugin/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Test
        run: go test -race -v ./...
  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOEKN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            sievelau/mosdns:latest
            sievelau/mosdns:4
          cache-from: type=gha
          cache-to: type=gha,mode=max
